### ISSUE TITLE
你的头像像素好低

### ISSUE THREAD

**Issue by iljyya** [rizhilee/Beautyacticle#1]
http://image.baidu.com/n/pc_list?queryImageUrl=https%3A%2F%2Favatars0.githubusercontent.com%2Fu%2F3689377%3Fv%3D3%26s%3D460&querySign=699022263%2C1390998314&fm=result&pos=moresize#tab=same

**Comment by NicodeLee** [comment]
谢提醒，已更新。
如果对这个项目有什么建议跟想法，欢迎热烈拍砖。
