### ISSUE TITLE
最美文字客户端无法访问

### ISSUE THREAD

**Issue by lhfly5201314** [rizhilee/Beautyacticle#3]
Hi，亲爱的Lee。很喜欢的你的 最美文字！感谢您把这么好的作品给开源出来了！
这两天在学习您的源码，但是把项目部署到手机，无法访问服务器，从您给网站上
直接下载app安装也是一样的，文字那个fragment收不到任何数据，把代码里面url
直接粘贴到浏览器里面，提示  您所访问的网站发生故障！是您在新浪上的部署流量
不够了还是怎么着了？？期待您的回复！ -------David

**Comment by NicodeLee** [comment]
谢谢你的关注，已经好了。
最近更新了客户端的第三方库代码。
功能交互也做了些调整。

**Comment by lhfly5201314** [comment]
嗯，嗯，谢谢您的劳动成果！我今天忽然发现客户端收到数据了，被界面给经验到了，体验非常棒！一定好好学习源码，太赞了！！！

**Comment by lhfly5201314** [comment]
楼主，你太棒了！一己之力做出这么好的app，而且自己找到那么多好素材，全能啊！看来我需要把你今天更新的最新代码给下载下来看了。有好多问题想向你请教。不知道能不能加您的微博或者其他的社交工具啊？？谢谢

**Comment by NicodeLee** [comment]
最近在学下前端，做个简单的后台跟web版，这是今年的计划了。

**Comment by lhfly5201314** [comment]
强，学无止境！你这是要成全站工栈的节奏啊！看好！看好！
